version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    groups:
      unocss:
        applies-to: version-updates
        patterns:
          - '@unocss/*'
          - 'unocss'
