// This file is auto-generated by @hey-api/openapi-ts

export const CreateRecipeDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: 'The name of the recipe',
            example: 'Spaghetti Carbonara'
        },
        description: {
            type: 'string',
            description: 'The description of the recipe',
            example: 'A classic Italian pasta dish'
        }
    },
    required: ['name', 'description']
} as const;

export const RecipeSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            description: 'The unique identifier of the recipe',
            example: '123e4567-e89b-12d3-a456-426614174000'
        },
        name: {
            type: 'string',
            description: 'The name of the recipe',
            example: 'Spaghetti Carbonara'
        },
        description: {
            type: 'string',
            description: 'The description of the recipe',
            example: 'A classic Italian pasta dish'
        }
    },
    required: ['id', 'name', 'description']
} as const;

export const UpdateRecipeDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            description: 'The name of the recipe',
            example: 'Spaghetti Carbonara'
        },
        description: {
            type: 'string',
            description: 'Der eindeutige Benutzername',
            example: 'johndoe'
        }
    },
    required: ['name', 'description']
} as const;

export const LoginUserDtoSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            description: 'Username of the user',
            example: 'john_doe'
        },
        password: {
            type: 'string',
            description: 'Password of the user',
            example: 'password123'
        }
    },
    required: ['username', 'password']
} as const;

export const LoginResponseDtoSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string',
            description: 'Access token for the user to authenticate'
        }
    },
    required: ['accessToken']
} as const;

export const CreateUserDtoSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            description: 'Username of the user',
            example: 'john_doe'
        },
        password: {
            type: 'string',
            description: 'Password of the user',
            example: 'password123'
        }
    },
    required: ['username', 'password']
} as const;

export const UserResponseDtoSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            description: 'The username of the user',
            example: 'john_doe'
        }
    },
    required: ['username']
} as const;