// This file is auto-generated by @hey-api/openapi-ts

export type RecipeIngredientRequestDto = {
    name: string;
    unit: string;
    amount: number;
};

export type RecipeRequestDto = {
    /**
     * Name of the recipe
     */
    name: string;
    /**
     * Description of the recipe
     */
    description?: string;
    /**
     * The recipe source
     */
    source?: string;
    /**
     * The number of servings
     */
    servings?: number;
    /**
     * The recipe duration in minutes
     */
    duration?: number;
    /**
     * The recipe ingredients
     */
    ingredients?: Array<RecipeIngredientRequestDto>;
    /**
     * The recipe instructions
     */
    instructions?: string;
    /**
     * The recipe nutrition
     */
    nutrition?: string;
    /**
     * The recipe notes
     */
    notes?: string;
};

export type RecipeIngredientResponseDto = {
    name: string;
    unit: string;
    amount: number;
};

export type RecipeResponseDto = {
    /**
     * The id of the recipe
     */
    id: string;
    /**
     * Name of the recipe
     */
    name: string;
    /**
     * Description of the recipe
     */
    description?: string;
    /**
     * The recipe source
     */
    source?: string;
    /**
     * The number of servings
     */
    servings?: number;
    /**
     * The recipe duration in minutes
     */
    duration?: number;
    /**
     * The recipe ingredients
     */
    ingredients?: Array<RecipeIngredientResponseDto>;
    /**
     * The recipe instructions
     */
    instructions?: string;
    /**
     * The recipe nutrition
     */
    nutrition?: string;
    /**
     * The recipe notes
     */
    notes?: string;
    /**
     * The image url the recipe image
     */
    imageUrl?: string;
};

export type PaginationSortOrder = 1 | -1;

export type RecipeResponseFlatDto = {
    /**
     * The id of the recipe
     */
    id: string;
    /**
     * Name of the recipe
     */
    name: string;
    /**
     * Description of the recipe
     */
    description?: string;
    /**
     * The recipe source
     */
    source?: string;
    /**
     * The number of servings
     */
    servings?: number;
    /**
     * The recipe duration in minutes
     */
    duration?: number;
    /**
     * The recipe instructions
     */
    instructions?: string;
    /**
     * The recipe nutrition
     */
    nutrition?: string;
    /**
     * The recipe notes
     */
    notes?: string;
    /**
     * The image url the recipe image
     */
    imageUrl?: string;
};

export type RecipePaginatedResponseDto = {
    total: number;
    /**
     * The page number
     */
    page: number;
    /**
     * The page size
     */
    pageSize: number;
    /**
     * The order by attribute
     */
    orderBy?: string;
    /**
     * The sort order
     */
    sortOrder?: PaginationSortOrder;
    content: Array<RecipeResponseFlatDto>;
};

export type AuthRequestDto = {
    /**
     * Username of the user
     */
    username: string;
    /**
     * Password of the user
     */
    password: string;
};

export type AuthResponseDto = {
    /**
     * Access token for the user to authenticate
     */
    accessToken: string;
};

export type AuthRegisterRequestDto = {
    /**
     * Username of the user
     */
    username: string;
    /**
     * Password of the user
     */
    password: string;
};

export type UserResponseDto = {
    /**
     * The id of the user
     */
    id: string;
    /**
     * Username of the user
     */
    username: string;
};

export type IngredientResponseDto = {
    id: string;
    name: string;
};

export type IngredientPaginatedResponseDto = {
    total: number;
    /**
     * The page number
     */
    page: number;
    /**
     * The page size
     */
    pageSize: number;
    /**
     * The order by attribute
     */
    orderBy?: string;
    /**
     * The sort order
     */
    sortOrder?: PaginationSortOrder;
    content: Array<IngredientResponseDto>;
};

export type CreatePlanMealDto = {
    dayIndex: number;
    recipeId: string;
};

export type CreatePlanDto = {
    name: string;
    days: number;
    meals?: Array<CreatePlanMealDto>;
};

export type PlanResponseMealRecipeDto = {
    /**
     * The id of the recipe
     */
    id: string;
    /**
     * Name of the recipe
     */
    name: string;
    /**
     * Description of the recipe
     */
    description?: string;
    /**
     * The recipe source
     */
    source?: string;
    /**
     * The number of servings
     */
    servings?: number;
    /**
     * The recipe duration in minutes
     */
    duration?: number;
    /**
     * The recipe instructions
     */
    instructions?: string;
    /**
     * The recipe nutrition
     */
    nutrition?: string;
    /**
     * The recipe notes
     */
    notes?: string;
    /**
     * The image url the recipe image
     */
    imageUrl?: string;
};

export type PlanResponseMealDto = {
    id: string;
    dayIndex: number;
    recipe: PlanResponseMealRecipeDto;
};

export type PlanResponseDto = {
    id: string;
    name: string;
    days: number;
    /**
     * The plan meals
     */
    meals?: Array<PlanResponseMealDto>;
};

export type PlanResponseFlatDto = {
    id: string;
    name: string;
    days: number;
};

export type PlanResponsePaginatedSimpleDto = {
    total: number;
    content: Array<PlanResponseFlatDto>;
};

export type PlanRequestMealDto = {
    dayIndex: number;
    recipeId: string;
};

export type PlanRequestDto = {
    name: string;
    days: number;
    meals?: Array<PlanRequestMealDto>;
};

export type ImportType = 'mela';

export type ImportRecipeDto = {
    url: string;
};

export type MessageType = 'updatedByProduct' | 'updatedByRecipe' | 'createdByRecipe' | 'createdByProduct';

export type LogEntryDto = {
    /**
     * The i18n message key
     */
    messageType: MessageType;
    /**
     * The i18n message properties
     */
    messageProperties?: {
        [key: string]: unknown;
    };
};

export type ProductResponseDto = {
    id: string;
    name: string;
    unit: string;
    amount: number;
    log: Array<LogEntryDto>;
};

export type ProductPaginatedResponseDto = {
    total: number;
    /**
     * The page number
     */
    page: number;
    /**
     * The page size
     */
    pageSize: number;
    /**
     * The order by attribute
     */
    orderBy?: string;
    /**
     * The sort order
     */
    sortOrder?: PaginationSortOrder;
    content: Array<ProductResponseDto>;
};

export type ProductRequestDto = {
    name: string;
    unit: string;
    amount: number;
};

export type ScheduledMealRequestDto = {
    recipeId: string;
    datetime: string;
    done?: boolean;
};

export type ScheduledMealResponseDto = {
    id: string;
    datetime: string;
    done?: boolean;
    recipe: RecipeResponseDto;
};

export type ScheduledMealResponsePaginatedDto = {
    total: number;
    content: Array<ScheduledMealResponseDto>;
};

export type GetRecipesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The page number
         */
        page: number;
        /**
         * The page size
         */
        pageSize: number;
        /**
         * The order by attribute
         */
        orderBy?: string;
        /**
         * The sort order
         */
        sortOrder?: PaginationSortOrder;
        /**
         * The filter
         */
        filter?: string;
    };
    url: '/v1/recipes';
};

export type GetRecipesResponses = {
    200: RecipePaginatedResponseDto;
};

export type GetRecipesResponse = GetRecipesResponses[keyof GetRecipesResponses];

export type CreateRecipeData = {
    body: RecipeRequestDto;
    path?: never;
    query?: never;
    url: '/v1/recipes';
};

export type CreateRecipeResponses = {
    /**
     * Recipe successfully created
     */
    201: RecipeResponseDto;
};

export type CreateRecipeResponse = CreateRecipeResponses[keyof CreateRecipeResponses];

export type DeleteRecipeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/recipes/{id}';
};

export type DeleteRecipeErrors = {
    /**
     * Recipe not found
     */
    404: unknown;
    /**
     * Recipe is in use by a plan
     */
    409: unknown;
};

export type DeleteRecipeResponses = {
    /**
     * Successfully deleted the recipe
     */
    200: unknown;
};

export type GetRecipeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/recipes/{id}';
};

export type GetRecipeErrors = {
    /**
     * Recipe not found
     */
    404: unknown;
};

export type GetRecipeResponses = {
    /**
     * Successfully retrieved the recipe
     */
    200: RecipeResponseDto;
};

export type GetRecipeResponse = GetRecipeResponses[keyof GetRecipeResponses];

export type UpdateRecipeData = {
    body: RecipeRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/recipes/{id}';
};

export type UpdateRecipeErrors = {
    /**
     * Recipe not found
     */
    404: unknown;
};

export type UpdateRecipeResponses = {
    /**
     * Successfully updated the recipe
     */
    200: RecipeResponseDto;
};

export type UpdateRecipeResponse = UpdateRecipeResponses[keyof UpdateRecipeResponses];

export type UserLoginData = {
    body: AuthRequestDto;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type UserLoginResponses = {
    /**
     * Successfully logged in
     */
    200: AuthResponseDto;
};

export type UserLoginResponse = UserLoginResponses[keyof UserLoginResponses];

export type UserRegisterData = {
    /**
     * Daten zur Erstellung eines neuen Benutzers
     */
    body: AuthRegisterRequestDto;
    path?: never;
    query?: never;
    url: '/v1/auth/register';
};

export type UserRegisterErrors = {
    /**
     * User already exists
     */
    409: unknown;
};

export type UserRegisterResponses = {
    /**
     * User successfully registered
     */
    201: unknown;
};

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/profile';
};

export type GetProfileResponses = {
    /**
     * Successfully retrieved the current user
     */
    200: UserResponseDto;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type GetIngredientsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The page number
         */
        page: number;
        /**
         * The page size
         */
        pageSize: number;
        /**
         * The order by attribute
         */
        orderBy?: string;
        /**
         * The sort order
         */
        sortOrder?: PaginationSortOrder;
        /**
         * The filter
         */
        filter?: string;
    };
    url: '/v1/ingredients';
};

export type GetIngredientsResponses = {
    200: IngredientPaginatedResponseDto;
};

export type GetIngredientsResponse = GetIngredientsResponses[keyof GetIngredientsResponses];

export type GetTemplatesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The page number
         */
        page: number;
        /**
         * The page size
         */
        pageSize: number;
        /**
         * The order by attribute
         */
        orderBy?: string;
        /**
         * The sort order
         */
        sortOrder?: PaginationSortOrder;
        /**
         * The filter
         */
        filter?: string;
    };
    url: '/v1/templates';
};

export type GetTemplatesResponses = {
    200: PlanResponsePaginatedSimpleDto;
};

export type GetTemplatesResponse = GetTemplatesResponses[keyof GetTemplatesResponses];

export type CreatePlanData = {
    body: CreatePlanDto;
    path?: never;
    query?: never;
    url: '/v1/templates';
};

export type CreatePlanResponses = {
    201: PlanResponseDto;
};

export type CreatePlanResponse = CreatePlanResponses[keyof CreatePlanResponses];

export type RemoveTemplateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/templates/{id}';
};

export type RemoveTemplateErrors = {
    404: unknown;
};

export type RemoveTemplateResponses = {
    200: unknown;
};

export type GetTemplateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/templates/{id}';
};

export type GetTemplateErrors = {
    404: unknown;
};

export type GetTemplateResponses = {
    200: PlanResponseDto;
};

export type GetTemplateResponse = GetTemplateResponses[keyof GetTemplateResponses];

export type UpdateTemplateData = {
    body: PlanRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/templates/{id}';
};

export type UpdateTemplateErrors = {
    404: unknown;
};

export type UpdateTemplateResponses = {
    200: PlanResponseDto;
};

export type UpdateTemplateResponse = UpdateTemplateResponses[keyof UpdateTemplateResponses];

export type ImportBackupData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query: {
        type: ImportType;
    };
    url: '/v1/data/import/recipes';
};

export type ImportBackupResponses = {
    200: unknown;
};

export type ScrapRecipeData = {
    body: ImportRecipeDto;
    path?: never;
    query?: never;
    url: '/v1/data/scrap/recipe';
};

export type ScrapRecipeErrors = {
    406: unknown;
};

export type ScrapRecipeResponses = {
    200: RecipeResponseDto;
};

export type ScrapRecipeResponse = ScrapRecipeResponses[keyof ScrapRecipeResponses];

export type GetProductsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The page number
         */
        page: number;
        /**
         * The page size
         */
        pageSize: number;
        /**
         * The order by attribute
         */
        orderBy?: string;
        /**
         * The sort order
         */
        sortOrder?: PaginationSortOrder;
        /**
         * The filter
         */
        filter?: string;
    };
    url: '/v1/products';
};

export type GetProductsResponses = {
    200: ProductPaginatedResponseDto;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type DeleteProductData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/products/{id}';
};

export type DeleteProductErrors = {
    404: unknown;
};

export type DeleteProductResponses = {
    200: unknown;
};

export type GetProductData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/products/{id}';
};

export type GetProductErrors = {
    404: unknown;
};

export type GetProductResponses = {
    200: ProductResponseDto;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type UpdateProductData = {
    body: ProductRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/products/{id}';
};

export type UpdateProductErrors = {
    404: unknown;
};

export type UpdateProductResponses = {
    200: ProductResponseDto;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type GetMealsData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
    };
    url: '/v1/meals';
};

export type GetMealsResponses = {
    200: ScheduledMealResponsePaginatedDto;
};

export type GetMealsResponse = GetMealsResponses[keyof GetMealsResponses];

export type CreateMealData = {
    body: ScheduledMealRequestDto;
    path?: never;
    query?: never;
    url: '/v1/meals';
};

export type CreateMealResponses = {
    201: ScheduledMealResponseDto;
};

export type CreateMealResponse = CreateMealResponses[keyof CreateMealResponses];

export type DeleteMealData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/meals/{id}';
};

export type DeleteMealErrors = {
    404: unknown;
};

export type DeleteMealResponses = {
    200: unknown;
};

export type GetMealData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/meals/{id}';
};

export type GetMealErrors = {
    404: unknown;
};

export type GetMealResponses = {
    200: ScheduledMealResponseDto;
};

export type GetMealResponse = GetMealResponses[keyof GetMealResponses];

export type UpdateMealData = {
    body: ScheduledMealRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/meals/{id}';
};

export type UpdateMealErrors = {
    404: unknown;
};

export type UpdateMealResponses = {
    200: ScheduledMealResponseDto;
};

export type UpdateMealResponse = UpdateMealResponses[keyof UpdateMealResponses];