// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCreateRecipeDto = z.object({
    name: z.string(),
    description: z.string().optional(),
    image: z.string().optional()
});

export const zRecipe = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    url: z.string()
});

export const zPaginationResponseDto = z.object({
    page: z.number().default(1),
    pageSize: z.number().default(10),
    orderBy: z.string().optional(),
    sortOrder: z.string().optional(),
    content: z.array(z.string()),
    total: z.number()
});

export const zUpdateRecipeDto = z.object({
    name: z.string(),
    description: z.string().optional(),
    image: z.string().optional()
});

export const zLoginUserDto = z.object({
    username: z.string(),
    password: z.string()
});

export const zLoginResponseDto = z.object({
    accessToken: z.string()
});

export const zCreateUserDto = z.object({
    username: z.string(),
    password: z.string()
});

export const zUserResponseDto = z.object({
    username: z.string()
});

export const zGetRecipesResponse = zPaginationResponseDto.merge(z.object({
    content: z.array(zRecipe).optional()
}));

export const zCreateRecipeResponse = zRecipe;

export const zGetRecipeResponse = zRecipe;

export const zUpdateRecipeResponse = zRecipe;

export const zUserLoginResponse = zLoginResponseDto;

export const zGetProfileResponse = zUserResponseDto;