// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zRecipeRequestDto = z.object({
    name: z.string(),
    description: z.string().optional()
});

export const zRecipeResponseDto = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string().optional(),
    imageUrl: z.string().optional()
});

export const zPaginationSortOrder = z.enum([
    'ASC',
    'DESC'
]);

export const zPaginationResponseDto = z.object({
    page: z.number().default(1),
    pageSize: z.number().default(10),
    orderBy: z.string().optional(),
    sortOrder: zPaginationSortOrder.optional(),
    content: z.array(z.array(z.unknown())),
    total: z.number()
});

export const zAuthRequestDto = z.object({
    username: z.string(),
    password: z.string()
});

export const zAuthResponseDto = z.object({
    accessToken: z.string()
});

export const zUserResponseDto = z.object({
    id: z.string(),
    username: z.string()
});

export const zGetRecipesResponse = zPaginationResponseDto.merge(z.object({
    content: z.array(zRecipeResponseDto).optional()
}));

export const zCreateRecipeResponse = zRecipeResponseDto;

export const zGetRecipeResponse = zRecipeResponseDto;

export const zUpdateRecipeResponse = zRecipeResponseDto;

export const zUploadImageResponse = zRecipeResponseDto;

export const zUpdateImageResponse = zRecipeResponseDto;

export const zUserLoginResponse = zAuthResponseDto;

export const zGetProfileResponse = zUserResponseDto;